// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using techlingo.projeto.Repository.Context;

#nullable disable

namespace techlingo.projeto.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("techlingo.projeto.Models.Aluno.AlunoAulasCursadasModel", b =>
                {
                    b.Property<int>("id_aula_cursada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_aula_cursada");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_aula_cursada"));

                    b.Property<DateTime?>("dt_termino")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_termino");

                    b.Property<int>("id_aluno_cursante")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_aluno_cursante");

                    b.Property<int>("id_aula")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_aula");

                    b.Property<string>("st_status")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("st_status");

                    b.HasKey("id_aula_cursada");

                    b.HasIndex("id_aluno_cursante");

                    b.HasIndex("id_aula");

                    b.ToTable("TL_AULA_CURSADA");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Aluno.AlunoCursosCursadosModel", b =>
                {
                    b.Property<int>("id_aluno_cursante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_aluno_cursante");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_aluno_cursante"));

                    b.Property<DateTime?>("dt_entrada")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_entrada");

                    b.Property<DateTime?>("dt_termino")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_termino");

                    b.Property<int>("id_aluno")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_aluno");

                    b.Property<int>("id_curso")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_curso");

                    b.Property<string>("st_status")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("st_status");

                    b.HasKey("id_aluno_cursante");

                    b.HasIndex("id_aluno");

                    b.HasIndex("id_curso");

                    b.ToTable("TL_ALUNO_CURSO");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Aluno.AlunoModel", b =>
                {
                    b.Property<int>("id_aluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_aluno");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_aluno"));

                    b.Property<string>("ds_email")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_email");

                    b.Property<string>("ds_senha")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_senha");

                    b.Property<DateTime?>("dt_alteracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime?>("dt_criacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_criacao");

                    b.Property<DateTime?>("dt_nascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_nascimento");

                    b.Property<int>("id_plano")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_plano");

                    b.Property<string>("nm_aluno")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_aluno");

                    b.Property<string>("nr_cpf")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nr_cpf");

                    b.HasKey("id_aluno");

                    b.HasIndex("id_plano");

                    b.ToTable("TL_ALUNO");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Cursos.AulaConteudoModel", b =>
                {
                    b.Property<int>("id_aula_conteudo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_aula_conteudo");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_aula_conteudo"));

                    b.Property<string>("ds_descricao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_descricao");

                    b.Property<string>("ds_link_video")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_link_video");

                    b.Property<string>("ds_titulo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_titulo");

                    b.Property<int>("id_aula")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_aula");

                    b.HasKey("id_aula_conteudo");

                    b.HasIndex("id_aula")
                        .IsUnique();

                    b.ToTable("TL_AULA_CONTEUDO");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Cursos.AulaQuizModel", b =>
                {
                    b.Property<int>("id_quiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_quiz");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_quiz"));

                    b.Property<string>("ds_descricao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_descricao");

                    b.Property<string>("ds_pergunta")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_pergunta");

                    b.Property<string>("ds_pergunta2")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_pergunta2");

                    b.Property<string>("ds_pergunta3")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_pergunta3");

                    b.Property<string>("ds_resposta")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_resposta");

                    b.Property<string>("ds_titulo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_titulo");

                    b.Property<int>("id_aula_conteudo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_aula_conteudo");

                    b.HasKey("id_quiz");

                    b.HasIndex("id_aula_conteudo")
                        .IsUnique();

                    b.ToTable("TL_AULA_QUIZ");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Cursos.AulasModel", b =>
                {
                    b.Property<int>("id_aula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_aula");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_aula"));

                    b.Property<DateTime?>("dt_criacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_criacao");

                    b.Property<int>("id_curso")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_curso");

                    b.Property<string>("nm_aula")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_aula");

                    b.Property<int?>("nr_aula")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("nr_aula");

                    b.HasKey("id_aula");

                    b.HasIndex("id_curso");

                    b.ToTable("TL_AULAS");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Cursos.CursosModel", b =>
                {
                    b.Property<int>("id_curso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_curso");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_curso"));

                    b.Property<string>("ds_curso")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_curso");

                    b.Property<DateTime?>("dt_criacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_criacao");

                    b.Property<string>("nm_curso")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_curso");

                    b.HasKey("id_curso");

                    b.ToTable("TL_CURSOS");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Planos.PlanoModel", b =>
                {
                    b.Property<int>("id_plano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_plano");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_plano"));

                    b.Property<string>("nm_plano")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_plano");

                    b.Property<decimal?>("vl_plano")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("vl_plano");

                    b.HasKey("id_plano");

                    b.ToTable("TL_PLANOS");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Aluno.AlunoAulasCursadasModel", b =>
                {
                    b.HasOne("techlingo.projeto.Models.Aluno.AlunoCursosCursadosModel", "cursante")
                        .WithMany("aulas_cursadas")
                        .HasForeignKey("id_aluno_cursante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techlingo.projeto.Models.Cursos.AulasModel", "aula")
                        .WithMany("alunos")
                        .HasForeignKey("id_aula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aula");

                    b.Navigation("cursante");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Aluno.AlunoCursosCursadosModel", b =>
                {
                    b.HasOne("techlingo.projeto.Models.Aluno.AlunoModel", "aluno")
                        .WithMany("cursosCursados")
                        .HasForeignKey("id_aluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techlingo.projeto.Models.Cursos.CursosModel", "curso")
                        .WithMany("cursantes")
                        .HasForeignKey("id_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("curso");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Aluno.AlunoModel", b =>
                {
                    b.HasOne("techlingo.projeto.Models.Planos.PlanoModel", "plano")
                        .WithMany("aluno")
                        .HasForeignKey("id_plano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("plano");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Cursos.AulaConteudoModel", b =>
                {
                    b.HasOne("techlingo.projeto.Models.Cursos.AulasModel", "aula")
                        .WithOne("conteudo")
                        .HasForeignKey("techlingo.projeto.Models.Cursos.AulaConteudoModel", "id_aula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aula");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Cursos.AulaQuizModel", b =>
                {
                    b.HasOne("techlingo.projeto.Models.Cursos.AulaConteudoModel", "conteudo")
                        .WithOne("quiz")
                        .HasForeignKey("techlingo.projeto.Models.Cursos.AulaQuizModel", "id_aula_conteudo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("conteudo");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Cursos.AulasModel", b =>
                {
                    b.HasOne("techlingo.projeto.Models.Cursos.CursosModel", "curso")
                        .WithMany("aulas")
                        .HasForeignKey("id_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("curso");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Aluno.AlunoCursosCursadosModel", b =>
                {
                    b.Navigation("aulas_cursadas");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Aluno.AlunoModel", b =>
                {
                    b.Navigation("cursosCursados");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Cursos.AulaConteudoModel", b =>
                {
                    b.Navigation("quiz");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Cursos.AulasModel", b =>
                {
                    b.Navigation("alunos");

                    b.Navigation("conteudo");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Cursos.CursosModel", b =>
                {
                    b.Navigation("aulas");

                    b.Navigation("cursantes");
                });

            modelBuilder.Entity("techlingo.projeto.Models.Planos.PlanoModel", b =>
                {
                    b.Navigation("aluno");
                });
#pragma warning restore 612, 618
        }
    }
}
